name: Windows LiteManager

on:
 workflow dispatch:

jobs:
   build:
       name: Start Building...
       runs-on: windows-latest
       timeout-minutes: 9999

  steps:
     -name: Downloading & Installing Essentials
run: 

Invoke-WebRequest -Url "https://gitlab.com/chamod12/1m_win-18_github_rdp/-/raw/main/Downloads.bat" -Outfile "Down cmd /c Downloads.bat

     -name: Connect to LiteManager
      run: cmd /c show.bat

     -name: Time Counter
       run: cmd /c loop.bat
